apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ekglue-reader
rules:
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "watch", "list"]
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: ["get", "watch", "list"]
